/* eslint-disable react/no-children-prop */
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "../components/sessionprovider/page";
import { getServerSession } from "next-auth";
import Layout from "../components/layouts/layout";

const disableNavbar = ["/login", "/register"];

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrains-mono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body
        className={`${jetbrainsMono.variable} ${geistMono.variable} antialiased bg-primary`}
      >
        <AuthProvider session={session}>
          <div className="">
            <Layout children={children}/>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
